version: '3'

services:
    esserver:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        volumes:
            - "./esdata:/usr/share/elasticsearch/data/"
        environment:
            - discovery.type=single-node
            - node.name=esserver
            - network.host=_site_
            - "ES_JAVA_OPTS=-Xms4g -Xmx20g"
            - "path.repo=/usr/share/elasticsearch/data/backups"
            - "search.max_buckets=1000000"
        ports:
            - "9200:9200"
            - "9300:9300"

    kibserver:
        image: docker.elastic.co/kibana/kibana:7.6.1
        volumes:
            - "./kibana.yaml:/usr/share/kibana/config/kibana.yml"
            - "./kibanadata:/usr/share/kibana/data"
        depends_on:
            - esserver

    logstash_server:
        build:
            context: .
            dockerfile: logstash.dockerfile
        volumes:
            - "./logstash.opts:/etc/init.d/logstash"
            - "./logstash.yaml:/usr/share/logstash/config/logstash.yml"
            - "./pipeline.conf:/usr/share/logstash/pipeline/logstash.conf"
            - "./logstash.patterns:/usr/share/logstash/pipeline/patterns/logstash.patterns"
            - "./analysis_service.patterns:/usr/share/logstash/pipeline/patterns/analysis_service.patterns"
            - "./content_service.patterns:/usr/share/logstash/pipeline/patterns/content_service.patterns"
            - "./referrers.patterns:/usr/share/logstash/pipeline/patterns/referrers.patterns"
            - "./logstashqueue:/var/queue"
            - "./ips_with_usage_types.csv:/ips.csv"
        ports:
            - "5043:5043"
        depends_on:
            - esserver
        environment:
             - "LS_OPTS=--quiet"
             - LS_JAVA_OPTS=-Xmx3g

    nginx:
        depends_on:
            - esserver
            - kibserver
        links:
            - kibserver
        image: nginx:1.17.4-alpine
        ports:
            - 6601:6601
        environment:
            - NGINX_PORT=6601
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./server.crt:/etc/nginx/conf.d/server.crt"
            - "./server.key:/etc/nginx/conf.d/server.key"
            - "./.htpasswd:/etc/nginx/conf.d/.htpasswd"
