version: '3'

services:
    esserver:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
        volumes:
            - "./esdata:/usr/share/elasticsearch/data/"
        environment:
            - discovery.type=single-node
            - node.name=esserver
            - network.host=_site_
            - "ES_JAVA_OPTS=-Xms4g -Xmx8g"

    kibserver:
        image: docker.elastic.co/kibana/kibana-oss:6.1.0
        volumes:
            - "./kibana.yaml:/usr/share/kibana/config/kibana.yml"
            - "./kibanadata:/usr/share/kibana/data"
        depends_on:
            - esserver

    logstash_server:
        build:
            context: .
            dockerfile: logstash.dockerfile
        volumes:
            - "./logstash.opts:/etc/init.d/logstash"
            - "./logstash.yaml:/usr/share/logstash/config/logstash.yml"
            - "./pipeline.conf:/usr/share/logstash/pipeline/logstash.conf"
            - "./logstash.patterns:/usr/share/logstash/pipeline/patterns/logstash.patterns"
            - "./logstashqueue:/var/queue"
        ports:
            - "5043:5043"
        depends_on:
            - esserver
        environment:
             - "LS_OPTS=--quiet"

    nginx:
        depends_on:
            - esserver
            - kibserver
        links:
            - kibserver
        image: nginx
        ports:
            - 6601:6601
        environment:
            - NGINX_PORT=6601
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./server.crt:/etc/nginx/conf.d/server.crt"
            - "./server.key:/etc/nginx/conf.d/server.key"
            - "./.htpasswd:/etc/nginx/conf.d/.htpasswd"
